---
- name: Create app directory
  action: file path=/u/apps/handy state=directory owner=handy group=handy mode=0755

- name: Configure nginx site
  action: copy src=handy.pittcsc.org dest=/etc/nginx/sites-available/handy.pittcsc.org
  notify: Restart nginx

- name: Enable nginx site
  action: file path=/etc/nginx/sites-enabled/handy.pittcsc.org src=/etc/nginx/sites-available/handy.pittcsc.org state=link force=yes
  notify: Restart nginx

- name: Allow HTTP traffic
  action: ufw direction=in proto=tcp port=80 rule=allow
  notify: Reload ufw

- name: Configure Eye
  action: copy src=handy.eye.rb dest=/u/eye/handy.eye
  notify: Reload Eye config

- name: Install dependencies
  action: apt package={{item}} state=installed
  with_items:
    - xorg
    - xvfb
    - wkhtmltopdf

- name: Install wkhtmltopdf shim
  action: copy src=wkhtmltopdf dest=/u/apps/handy/shared/bin/wkhtmltopdf owner=handy group=handy mode=0744
