---
- name: Install global Ruby
  action: command "/opt/rbenv/bin/rbenv install {{ var | ruby.global }} --skip-existing" creates="/opt/rbenv/versions/{{ ruby.global }}"
  when: ruby.global

- name: Check that global Ruby is set
  action: shell "/usr/bin/env rbenv global | grep ^{{ var | ruby.global }} -q" executable=/bin/bash
  when: ruby.global
  register: ruby.global_set

- name: Set global Ruby
  action: shell "/usr/bin/env rbenv global {{ var | ruby.global }}" executable=/bin/bash
  when: ruby.global and ruby.global_set.rc != 0
