---
- name: Install global Ruby
  action: shell /bin/bash -lc "rbenv install {{ ruby.global }} --skip-existing"
  when: ruby.global

- name: Set global Ruby
  action: shell /bin/bash -lc "rbenv global {{ ruby.global }}"
  when: ruby.global
