---
- name: Install Nagios
  action: apt pkg=nagios3=3.5.1-1ubuntu1 state=installed

- name: Delete default Nagios config files
  action: file path=/etc/nagios3/{{ item }} state=absent
  with_items:
    - commands.cfg
    - conf.d/contacts_nagios2.cfg
    - conf.d/extinfo_nagios2.cfg
    - conf.d/generic-host_nagios2.cfg
    - conf.d/generic-service_nagios2.cfg
    - conf.d/hostgroups_nagios2.cfg
    - conf.d/localhost_nagios2.cfg
    - conf.d/services_nagios2.cfg
    - conf.d/timeperiods_nagios2.cfg
  notify: Restart Nagios

- name: Create Nagios config directories
  action: file path=/etc/nagios3/conf.d/{{ item }} state=directory owner=nagios group=nagios
  with_items:
    - hosts

- name: Configure Nagios
  action: copy src={{ item }} dest=/etc/nagios3/{{ item }} owner=nagios group=nagios
  with_items:
    - nagios.cfg
    - htpasswd.users
  notify: Restart Nagios

- name: Install Nagios config for check_mk
  action: copy src=check_mk_objects.cfg dest=/etc/nagios3/conf.d/check_mk_objects.cfg owner=nagios group=nagios
  notify: Restart Nagios

- name: Uninstall NRPE plugin
  action: apt pkg=nagios-nrpe-plugin state=absent
  notify: Restart Nagios

- name: Allow HTTP traffic
  action: ufw direction=in proto=tcp port=80 rule=allow
  notify: Reload ufw
