---
- name: Create app directory
  action: file path=/u/apps/heaven state=directory owner=heaven group=heaven mode=0755

- name: Configure nginx site
  action: copy src=heaven.pittcsc.org dest=/etc/nginx/sites-available/heaven.pittcsc.org
  notify: Restart nginx

- name: Enable nginx site
  action: file path=/etc/nginx/sites-enabled/heaven.pittcsc.org src=/etc/nginx/sites-available/heaven.pittcsc.org state=link force=yes
  notify: Restart nginx

- name: Allow HTTP traffic
  action: ufw direction=in proto=tcp port=80 rule=allow
  notify: Reload ufw

- name: Set private SSH key
  action: template src=id_rsa dest=/home/heaven/.ssh/id_rsa

- name: Set public SSH key
  action: template src=id_rsa.pub dest=/home/heaven/.ssh/id_rsa.pub

- name: Configure Eye
  action: template src=heaven.eye.rb dest=/u/eye/heaven.eye
  notify: Reload Eye config
