---
- name: Configure nginx site
  action: copy src=steelhacks.pittcsc.org dest=/etc/nginx/sites-available/steelhacks.pittcsc.org
  notify: Restart nginx

- name: Enable nginx site
  action: file path=/etc/nginx/sites-enabled/steelhacks.pittcsc.org src=/etc/nginx/sites-available/steelhacks.pittcsc.org state=link force=yes
  notify: Restart nginx
