---
- name: Enable ufw
  action: ufw state=enabled

- name: Allow outbound public traffic
  action: ufw direction=outgoing policy=allow
  notify: Reload ufw

- name: Allow inbound traffic from internal hosts
  action: ufw direction=in proto=any from_ip={{ item }} rule=allow
  with_items:
    - 10.132.223.240  # gateway-01
    - 10.132.236.208  # ops-01
    - 10.132.250.45   # db-01
    - 10.132.243.53   # app-01
  notify: Reload ufw

- name: Deny inbound traffic from decommissioned internal hosts
  action: ufw direction=in proto=any from_ip={{ item }} rule=allow delete=yes
  with_items:
    - 10.132.224.20  # web-0l
  notify: Reload ufw

- name: Deny other inbound traffic
  action: ufw direction=incoming policy=deny
  notify: Reload ufw
