---
- name: Enable Sensu client service
  action: service name=sensu-client enabled=yes

- name: Configure Sensu client
  action: template src=conf.d/client.json dest=/etc/sensu/conf.d/client.json owner=sensu group=sensu mode=0640
  notify: Restart Sensu client
