---
- name: Install Nagios
  action: apt pkg=nagios3=3.5.1-1ubuntu1 state=installed

- name: Delete default Nagios config files
  action: file path=/etc/nagios3/{{ item }} state=absent
  with_items:
    - commands.cfg
    - conf.d/contacts_nagios2.cfg
    - conf.d/extinfo_nagios2.cfg
    - conf.d/generic-host_nagios2.cfg
    - conf.d/generic-service_nagios2.cfg
    - conf.d/hostgroups_nagios2.cfg
    - conf.d/localhost_nagios2.cfg
    - conf.d/services_nagios2.cfg
    - conf.d/timeperiods_nagios2.cfg
  notify: Restart Nagios

- name: Create Nagios config directories
  action: file path=/etc/nagios3/conf.d/{{ item }} state=directory owner=nagios group=nagios
  with_items:
    - hosts

- name: Configure Nagios
  action: copy src=nagios.cfg dest=/etc/nagios3/nagios.cfg owner=nagios group=nagios
  notify: Restart Nagios

- name: Add custom Nagios config
  action: copy src=conf/{{ item }} dest=/etc/nagios3/conf.d/{{ item }} owner=nagios group=nagios
  with_items:
    - contacts.cfg
    - hostgroups.cfg
    - hosts.cfg
    - services.cfg
    - timeperiods.cfg
    - commands.cfg
  notify: Restart Nagios

- name: Install NRPE plugin
  action: apt pkg=nagios-nrpe-plugin state=installed
  notify: Restart Nagios

- name: Allow HTTP traffic
  action: ufw direction=in proto=tcp port=80 rule=allow
  notify: Reload ufw
