---
- name: Install system Python and supporting utils
  action: apt package={{item}} state=installed
  with_items:
    - python
    - python-setuptools

- name: Install pip
  action: easy_install name=pip

- name: Install virtualenv
  action: pip name=virtualenv state=present
