---
- name: Create app directory
  action: file path=/u/apps/handy state=directory

- name: Configure nginx site
  action: copy src=handy.pittcsc.org dest=/etc/nginx/sites-enabled/handy.pittcsc.org
  notify: Restart nginx

- name: Allow HTTP traffic
  action: ufw direction=in proto=tcp port=80 rule=allow
  notify: Reload ufw
