- name: Install bind9
  apt: pkg={{item}} state=installed
  with_items:
    - bind9
    - bind9utils
    - bind9-doc

- name: Set bind9 options
  action: copy src=bind9 dest=/etc/default/bind9
  notify: Restart bind9

- name: Set named options
  action: template src=named.conf.options dest=/etc/bind/named.conf.options
  notify: Restart bind9

- name: Define named zones
  action: copy src=named.conf.local dest=/etc/bind/named.conf.local
  notify: Restart bind9

- name: Create zones directory
  action: file path=/etc/bind/zones state=directory

- name: Populate forward zone file for do-nyc3.pittcsc.org
  action: copy src=zones/db.do-nyc3.pittcsc.org dest=/etc/bind/zones/db.do-nyc3.pittcsc.org mode=0644
  notify: Restart bind9

- name: Populate reverse zone file for 132.10.in-addr.arpa
  action: copy src=zones/db.10.132 dest=/etc/bind/zones/db.10.132 mode=0644
  notify: Restart bind9
