---
- name: Install Jenkins dependencies
  action: apt pkg={{ item }} state=latest
  with_items:
    - python-pycurl

- name: Add key for Jenkins repository to APT
  action: apt_key url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: Add Jenkins repository to APT
  action: apt_repository repo="deb http://pkg.jenkins-ci.org/debian binary/" update_cache=yes

- name: Install Jenkins
  action: apt pkg=jenkins state=latest
  notify: Restart Jenkins

- name: Set Jenkins defaults
  action: copy src=defaults dest=/etc/default/jenkins
  notify: Restart Jenkins
