---
- name: Install Ansible dependencies
  action: apt pkg={{ item }} state=latest
  with_items:
    - software-properties-common
    - python-pycurl

- name: Add Ansible APT repository
  action: apt_repository repo=ppa:ansible/ansible state=present update_cache=true

- name: Install Ansible
  action: apt pkg=ansible state=installed

- name: Set Ansible options
  action: copy src=ansible.cfg dest=/etc/ansible/ansible.cfg
