---
- name: Install Graphite
  action: apt pkg={{ item }} state=installed
  with_items:
    - graphite-web
    - graphite-carbon

- name: Configure Graphite
  action: template src=local_settings.py dest=/etc/graphite/local_settings.py owner=root group=root mode=0640

- name: Enable Carbon
  action: copy src=carbon/default dest=/etc/default/graphite-carbon owner=root group=root mode=0644

- name: Configure Carbon
  action: copy src=carbon/{{ item }} dest=/etc/carbon/{{ item }} owner=root group=root mode=0644
  with_items:
    - carbon.conf
    - storage-schemas.conf
